# Architecture Workflow Configuration
name: architecture
description: "Collaborative architectural decision facilitation for AI-agent consistency. Replaces template-driven architecture with intelligent, adaptive conversation that produces a decision-focused architecture document optimized for preventing agent conflicts."
author: "BMad"

# Critical variables
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Input requirements - We work from PRD, Epics, and optionally UX Spec
recommended_inputs:
  - prd: "Product Requirements Document with FRs and NFRs"
  - epics: "Epic definitions with user stories and acceptance criteria"
  - ux_spec: "UX specification with interface designs and interaction patterns (optional)"

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
input_file_patterns:
  prd:
    whole: "{output_folder}/*prd*.md"
    sharded: "{output_folder}/*prd*/index.md"

  epics:
    whole: "{output_folder}/*epic*.md"
    sharded: "{output_folder}/*epic*/index.md"

  ux_design:
    whole: "{output_folder}/*ux*.md"
    sharded: "{output_folder}/*ux*/index.md"

  document_project:
    sharded: "{output_folder}/docs/index.md"

# Module path and component files
installed_path: "{project-root}/bmad/bmm/workflows/3-solutioning/architecture"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: "{installed_path}/architecture-template.md"

# Knowledge bases for intelligent decision making
decision_catalog: "{installed_path}/decision-catalog.yaml"
architecture_patterns: "{installed_path}/architecture-patterns.yaml"
pattern_categories: "{installed_path}/pattern-categories.csv"

# Output configuration
default_output_file: "{output_folder}/architecture.md"

# Workflow metadata
version: "1.3.2"
replaces: "architecture"
paradigm: "facilitation-driven"
execution_time: "30-90 minutes depending on user skill level"
features:
  - "Starter template discovery and integration"
  - "Dynamic version verification via web search"
  - "Adaptive facilitation by skill level"
  - "Decision-focused architecture"
  - "Novel pattern design for unique concepts"
  - "Intelligent pattern identification - LLM figures out what patterns matter"
  - "Implementation patterns for agent consistency"

standalone: true

# Web bundle configuration for standalone deployment
web_bundle:
  name: "architecture"
  description: "Collaborative architectural decision facilitation for AI-agent consistency. Replaces template-driven architecture with intelligent, adaptive conversation that produces a decision-focused architecture document optimized for preventing agent conflicts."
  author: "BMad"

  # Core workflow files (bmad/-relative paths)
  instructions: "bmad/bmm/workflows/3-solutioning/architecture/instructions.md"
  validation: "bmad/bmm/workflows/3-solutioning/architecture/checklist.md"
  template: "bmad/bmm/workflows/3-solutioning/architecture/architecture-template.md"

  # Knowledge base files for decision making
  decision_catalog: "bmad/bmm/workflows/3-solutioning/architecture/decision-catalog.yaml"
  architecture_patterns: "bmad/bmm/workflows/3-solutioning/architecture/architecture-patterns.yaml"
  pattern_categories: "bmad/bmm/workflows/3-solutioning/architecture/pattern-categories.csv"

  # Task dependencies
  adv_elicit_task: "bmad/core/tasks/adv-elicit.xml"

  # Default configuration values (can be overridden during bundle setup)
  defaults:
    user_name: "User"
    communication_language: "English"
    document_output_language: "English"
    user_skill_level: "intermediate"
    output_folder: "./output"

  # Input/output configuration for web deployment
  default_output_file: "{output_folder}/architecture.md"

  # Complete file list - ALL files this workflow depends on
  web_bundle_files:
    # Core workflow files
    - "bmad/bmm/workflows/3-solutioning/architecture/instructions.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/checklist.md"
    - "bmad/bmm/workflows/3-solutioning/architecture/architecture-template.md"

    # Knowledge base data files
    - "bmad/bmm/workflows/3-solutioning/architecture/decision-catalog.yaml"
    - "bmad/bmm/workflows/3-solutioning/architecture/architecture-patterns.yaml"
    - "bmad/bmm/workflows/3-solutioning/architecture/pattern-categories.csv"

    # Task dependencies (referenced in instructions.md)
    - "bmad/core/tasks/workflow.xml"
    - "bmad/core/tasks/adv-elicit.xml"
    - "bmad/core/tasks/adv-elicit-methods.csv"
