# UX/UI Specification Workflow
name: ux-spec
description: "UX/UI specification workflow for defining user experience and interface design. Creates comprehensive UX documentation including wireframes, user flows, component specifications, and design system guidelines."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/2-plan-workflows/ux"
instructions: "{installed_path}/instructions-ux.md"
template: "{installed_path}/ux-spec-template.md"

# Output configuration
default_output_file: "{output_folder}/ux-specification.md"
ai_frontend_prompt_file: "{output_folder}/ai-frontend-prompt.md"

# Recommended input documents
recommended_inputs:
  - prd: "{output_folder}/PRD.md"
  - product_brief: "{output_folder}/product-brief.md"
  - gdd: "{output_folder}/GDD.md"

web_bundle:
  name: "ux-spec"
  description: "UX/UI specification workflow for defining user experience and interface design. Creates comprehensive UX documentation including wireframes, user flows, component specifications, and design system guidelines."
  author: "BMad"
  instructions: "bmad/bmm/workflows/2-plan-workflows/ux/instructions-ux.md"
  web_bundle_files:
    - "bmad/bmm/workflows/2-plan-workflows/ux/instructions-ux.md"
    - "bmad/bmm/workflows/2-plan-workflows/ux/ux-spec-template.md"
