workflow:
  id: domain-research
  name: "Domain Research"
  module: bmm
  version: "6.0.0-alpha"
  description: "Collaborative exploration of domain-specific requirements, regulations, and patterns for complex projects"

  environment:
    # Inherit from parent workflow or set defaults
    user_name: "partner"
    user_skill_level: "intermediate"
    communication_language: "English"
    document_output_language: "English"
    date: "{system.date}"

  required_files:
    - instructions.md
    - template.md

  optional_files:
    - domain-knowledge-base.md

  outputs:
    - domain-brief.md

  metadata:
    category: "analysis"
    complexity: "medium"
    estimated_time: "30-45 minutes"
    prerequisites:
      - "Basic project understanding"
    when_to_use:
      - "Complex regulated domains (healthcare, finance, aerospace)"
      - "Novel technical domains requiring deep understanding"
      - "Before PRD when domain expertise needed"
      - "When compliance and regulations matter"
