# Edit Module - Module Editor Configuration
name: "edit-module"
description: "Edit existing BMAD modules (structure, agents, workflows, documentation) while following all best practices"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/bmad/bmb/config.yaml"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"

# Required Data Files - Critical for understanding module conventions
module_structure_guide: "{project-root}/bmad/bmb/workflows/create-module/module-structure.md"

# Related workflow editors
agent_editor: "{project-root}/bmad/bmb/workflows/edit-agent/workflow.yaml"
workflow_editor: "{project-root}/bmad/bmb/workflows/edit-workflow/workflow.yaml"

# Optional docs that can be used to understand the target module
recommended_inputs:
  - target_module: "Path to the module directory to edit"
  - bmm_module: "{project-root}/bmad/bmm/"
  - bmb_module: "{project-root}/bmad/bmb/"
  - cis_module: "{project-root}/bmad/cis/"
  - existing_agents: "{project-root}/bmad/*/agents/"
  - existing_workflows: "{project-root}/bmad/*/workflows/"

# Module path and component files
installed_path: "{project-root}/bmad/bmb/workflows/edit-module"
template: false # This is an action workflow - no template needed
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

standalone: true
# Web bundle configuration
