blank_issues_enabled: false
contact_links:
  - name: Discord Community Support
    url: https://discord.gg/gk8jAdXWmj
    about: Please join our Discord server for general questions and community discussion before opening an issue.
