# Epic and Story Decomposition Workflow
name: create-epics-and-stories
description: "Transform PRD requirements into bite-sized stories organized in epics for 200k context dev agents"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
project_name: "{config_source}:project_name"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/2-plan-workflows/prd/create-epics-and-stories"
instructions: "{installed_path}/instructions.md"
template: "{installed_path}/epics-template.md"

# Input files (from parent PRD workflow)
prd_file: "{output_folder}/PRD.md"

# Output files
default_output_file: "{output_folder}/epics.md"

# Optional input documents
recommended_inputs:
  - prd: "{output_folder}/PRD.md"
  - product_brief: "{output_folder}/product-brief.md"
  - domain_brief: "{output_folder}/domain-brief.md"

standalone: true
