name: sprint-planning
description: "Generate and manage the sprint status tracking file for Phase 4 implementation, extracting all epics and stories from epic files and tracking their status through the development lifecycle"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/sprint-planning"
instructions: "{installed_path}/instructions.md"
template: "{installed_path}/sprint-status-template.yaml"
validation: "{installed_path}/checklist.md"

# Variables and inputs
variables:
  # Project identification
  project_name: "{config_source}:project_name"
  project_key: "{config_source}:project_name" # Future: Jira project key, Linear workspace ID, etc.

  # Tracking system configuration
  tracking_system: "file-system" # Options: file-system, Future will support other options from config of mcp such as jira, linear, trello
  story_location: "{project-root}/docs/stories" # Relative path for file-system, Future will support URL for Jira/Linear/Trello
  story_location_absolute: "{config_source}:dev_story_location" # Absolute path for file operations

  # Source files (file-system only)
  epics_location: "{output_folder}" # Directory containing epic*.md files
  epics_pattern: "epic*.md" # Pattern to find epic files

  # Output configuration
  status_file: "{output_folder}/sprint-status.yaml"

# Output configuration
default_output_file: "{status_file}"

standalone: true

web_bundle: false
