# Technical Specification Workflow (Level 0)
name: tech-spec-sm
description: "Technical specification workflow for Level 0 projects (single atomic changes). Creates focused tech spec for bug fixes, single endpoint additions, or small isolated changes. Tech-spec only - no PRD needed."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
project_name: "{config_source}:project_name"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/2-plan-workflows/tech-spec"
instructions: "{installed_path}/instructions.md"
template: "{installed_path}/tech-spec-template.md"

# Story generation instructions (invoked based on level)
instructions_level0_story: "{installed_path}/instructions-level0-story.md"
instructions_level1_stories: "{installed_path}/instructions-level1-stories.md"

# Templates
user_story_template: "{installed_path}/user-story-template.md"
epics_template: "{installed_path}/epics-template.md"

# Output configuration
default_output_file: "{output_folder}/tech-spec.md"
user_story_file: "{output_folder}/user-story.md"
epics_file: "{output_folder}/epics.md"

# Recommended input documents (optional for Level 0)
recommended_inputs:
  - bug_report: "Bug description or issue ticket"
  - feature_request: "Brief feature description"

web_bundle:
  name: "tech-spec-sm"
  description: "Technical specification workflow for Level 0-1 projects. Creates focused tech spec with story generation. Level 0: tech-spec + user story. Level 1: tech-spec + epic/stories."
  author: "BMad"
  instructions: "bmad/bmm/workflows/2-plan-workflows/tech-spec/instructions.md"
  web_bundle_files:
    - "bmad/bmm/workflows/2-plan-workflows/tech-spec/instructions.md"
    - "bmad/bmm/workflows/2-plan-workflows/tech-spec/instructions-level0-story.md"
    - "bmad/bmm/workflows/2-plan-workflows/tech-spec/instructions-level1-stories.md"
    - "bmad/bmm/workflows/2-plan-workflows/tech-spec/tech-spec-template.md"
    - "bmad/bmm/workflows/2-plan-workflows/tech-spec/user-story-template.md"
    - "bmad/bmm/workflows/2-plan-workflows/tech-spec/epics-template.md"
