# Narrative Design Workflow
name: narrative
description: "Narrative design workflow for story-driven games and applications. Creates comprehensive narrative documentation including story structure, character arcs, dialogue systems, and narrative implementation guidance."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/2-plan-workflows/narrative"
instructions: "{installed_path}/instructions-narrative.md"
template: "{installed_path}/narrative-template.md"

# Output configuration
default_output_file: "{output_folder}/narrative-design.md"

# Recommended input documents
recommended_inputs:
  - game_brief: "{output_folder}/game-brief.md"
  - gdd: "{output_folder}/GDD.md"
  - product_brief: "{output_folder}/product-brief.md"

standalone: true

web_bundle:
  name: "narrative"
  description: "Narrative design workflow for story-driven games and applications. Creates comprehensive narrative documentation including story structure, character arcs, dialogue systems, and narrative implementation guidance."
  author: "BMad"
  instructions: "bmad/bmm/workflows/2-plan-workflows/narrative/instructions-narrative.md"
  web_bundle_files:
    - "bmad/bmm/workflows/2-plan-workflows/narrative/instructions-narrative.md"
    - "bmad/bmm/workflows/2-plan-workflows/narrative/narrative-template.md"
