# Edit Agent - Agent Editor Configuration
name: "edit-agent"
description: "Edit existing BMAD agents while following all best practices and conventions"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/bmad/bmb/config.yaml"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"

# Required Data Files - Critical for understanding agent conventions
agent_types: "{project-root}/bmad/bmb/workflows/create-agent/agent-types.md"
agent_architecture: "{project-root}/bmad/bmb/workflows/create-agent/agent-architecture.md"
agent_commands: "{project-root}/bmad/bmb/workflows/create-agent/agent-command-patterns.md"
communication_styles: "{project-root}/bmad/bmb/workflows/create-agent/communication-styles.md"

# Workflow execution engine reference
workflow_execution_engine: "{project-root}/bmad/core/tasks/workflow.xml"

# Optional docs that can be used to understand the target agent
recommended_inputs:
  - target_agent: "Path to the agent.yaml or agent.md file to edit"
  - example_agents: "{project-root}/bmad/bmm/agents/"
  - agent_activation_rules: "{project-root}/src/utility/models/agent-activation-ide.xml"

# Module path and component files
installed_path: "{project-root}/bmad/bmb/workflows/edit-agent"
template: false # This is an action workflow - no template needed
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

standalone: true
# Web bundle configuration
