# Product Requirements Document (PRD) Workflow
name: prd
description: "Unified PRD workflow for project levels 2-4. Produces strategic PRD and tactical epic breakdown. Hands off to architecture workflow for technical design. Note: Level 0-1 use tech-spec workflow."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
project_name: "{config_source}:project_name"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/2-plan-workflows/prd"
instructions: "{installed_path}/instructions.md"

# Templates
prd_template: "{installed_path}/prd-template.md"
epics_template: "{installed_path}/epics-template.md"

# Output files
status_file: "{output_folder}/bmm-workflow-status.md"
default_output_file: "{output_folder}/PRD.md"
epics_output_file: "{output_folder}/epics.md"
technical_decisions_file: "{output_folder}/technical-decisions.md"
technical_decisions_template: "{project-root}/bmad/bmm/_module-installer/assets/technical-decisions.md"

# Recommended input documents
recommended_inputs:
  - product_brief: "{output_folder}/product-brief.md"
  - market_research: "{output_folder}/market-research.md"

standalone: true

web_bundle:
  name: "prd"
  description: "Unified PRD workflow for project levels 2-4. Produces strategic PRD and tactical epic breakdown. Hands off to architecture workflow for technical design. Note: Level 0-1 use tech-spec workflow."
  author: "BMad"
  instructions: "bmad/bmm/workflows/2-plan-workflows/prd/instructions.md"
  web_bundle_files:
    - "bmad/bmm/workflows/2-plan-workflows/prd/instructions.md"
    - "bmad/bmm/workflows/2-plan-workflows/prd/prd-template.md"
    - "bmad/bmm/workflows/2-plan-workflows/prd/epics-template.md"
