# Test Architect workflow: test-design
name: testarch-test-design
description: "Plan risk mitigation and test coverage strategy before development with risk assessment and prioritization"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/testarch/test-design"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: "{installed_path}/test-design-template.md"

# Variables and inputs
variables:
  # Target scope
  epic_num: "" # Epic number for scoped design
  story_path: "" # Specific story for design (optional)
  design_level: "full" # full, targeted, minimal

  # Risk assessment configuration
  risk_assessment_enabled: true
  risk_threshold: 6 # Scores >= 6 are high-priority (probability × impact)
  risk_categories: "TECH,SEC,PERF,DATA,BUS,OPS" # Comma-separated

  # Coverage planning
  priority_levels: "P0,P1,P2,P3" # Test priorities
  test_levels: "e2e,api,integration,unit,component" # Test levels to consider
  selective_testing_strategy: "risk-based" # risk-based, coverage-based, hybrid

  # Output configuration
  output_file: "{output_folder}/test-design-epic-{epic_num}.md"
  include_risk_matrix: true
  include_coverage_matrix: true
  include_execution_order: true
  include_resource_estimates: true

  # Advanced options
  auto_load_knowledge: true # Load relevant knowledge fragments
  include_mitigation_plan: true
  include_gate_criteria: true
  standalone_mode: false # Can run without epic context

# Output configuration
default_output_file: "{output_folder}/test-design-epic-{epic_num}.md"

# Required tools
required_tools:
  - read_file # Read PRD, epics, stories, architecture docs
  - write_file # Create test design document
  - list_files # Find related documentation
  - search_repo # Search for existing tests and patterns

# Recommended inputs
recommended_inputs:
  - prd: "Product Requirements Document for context"
  - epics: "Epic documentation (epics.md or specific epic)"
  - story: "Story markdown with acceptance criteria"
  - architecture: "Architecture documents (solution-architecture.md, tech-spec)"
  - existing_tests: "Current test coverage for gap analysis"

tags:
  - qa
  - planning
  - test-architect
  - risk-assessment
  - coverage

execution_hints:
  interactive: false # Minimize prompts
  autonomous: true # Proceed without user input unless blocked
  iterative: true

web_bundle: false
