# Test Architect workflow: test-design
name: testarch-test-design
description: "Plan risk mitigation and test coverage strategy before development with risk assessment and prioritization"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/testarch/test-design"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: "{installed_path}/test-design-template.md"

# Variables and inputs
variables:
  design_level: "full" # full, targeted, minimal - scope of design effort

# Output configuration
default_output_file: "{output_folder}/test-design-epic-{epic_num}.md"

# Required tools
required_tools:
  - read_file # Read PRD, epics, stories, architecture docs
  - write_file # Create test design document
  - list_files # Find related documentation
  - search_repo # Search for existing tests and patterns

# Recommended inputs
recommended_inputs:
  - prd: "Product Requirements Document for context"
  - epics: "Epic documentation (epics.md or specific epic)"
  - story: "Story markdown with acceptance criteria"
  - architecture: "Architecture documents (architecture.md, tech-spec)"
  - existing_tests: "Current test coverage for gap analysis"

tags:
  - qa
  - planning
  - test-architect
  - risk-assessment
  - coverage

execution_hints:
  interactive: false # Minimize prompts
  autonomous: true # Proceed without user input unless blocked
  iterative: true

web_bundle: false
