# Game Design Document (GDD) Workflow
name: gdd
description: "Game Design Document workflow for all game project levels - from small prototypes to full AAA games. Generates comprehensive GDD with game mechanics, systems, progression, and implementation guidance."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmgd/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
game_dev_experience: "{config_source}:game_dev_experience"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmgd/workflows/2-design/gdd"
instructions: "{installed_path}/instructions-gdd.md"
template: "{installed_path}/gdd-template.md"
game_types_csv: "{installed_path}/game-types.csv"

# Output configuration
default_output_file: "{output_folder}/GDD.md"

# Game type references (loaded based on game type selection)
game_type_guides: "{installed_path}/game-types/"

# Recommended input documents
recommended_inputs:
  - game_brief: "{output_folder}/game-brief.md"
  - narrative_design: "{output_folder}/narrative-design.md"
  - market_research: "{output_folder}/market-research.md"

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
input_file_patterns:
  game_brief:
    whole: "{output_folder}/*game-brief*.md"
    sharded: "{output_folder}/*game-brief*/index.md"

  research:
    whole: "{output_folder}/*research*.md"
    sharded: "{output_folder}/*research*/index.md"

  document_project:
    sharded: "{output_folder}/docs/index.md"

standalone: true

web_bundle:
  name: "gdd"
  description: "Game Design Document workflow for all game project levels - from small prototypes to full AAA games. Generates comprehensive GDD with game mechanics, systems, progression, and implementation guidance."
  author: "BMad"
  instructions: "bmad/bmgd/workflows/2-design/gdd/instructions-gdd.md"
  web_bundle_files:
    - "bmad/bmgd/workflows/2-design/gdd/instructions-gdd.md"
    - "bmad/bmgd/workflows/2-design/gdd/gdd-template.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types.csv"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/action-platformer.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/adventure.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/card-game.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/fighting.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/horror.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/idle-incremental.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/metroidvania.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/moba.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/party-game.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/puzzle.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/racing.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/rhythm.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/roguelike.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/rpg.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/sandbox.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/shooter.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/simulation.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/sports.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/strategy.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/survival.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/text-based.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/tower-defense.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/turn-based-tactics.md"
    - "bmad/bmgd/workflows/2-design/gdd/game-types/visual-novel.md"
