# {TITLE} Workflow Template Configuration
name: "{WORKFLOW_CODE}"
description: "{WORKFLOW_DESCRIPTION}"
author: "BMad"

# Critical variables load from config_source
# Add Additional Config Pulled Variables Here
config_source: "{project-root}/{module-code}/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Required Data Files - HALT if missing!
# optional, can be omitted
brain_techniques: "{installed_path}/{critical-data-file.csv}" # example, can be other formats or URLs

# Optional docs that if loaded on start to kickstart this workflow or used at some point, these are meant to be suggested inputs for the user
recommended_inputs: # optional, can be omitted
  - example_input: "{project-root}/{path/to/file.md}"

# Module path and component files
installed_path: "{project-root}/bmad/{module-code}/workflows/{workflow-code}"
template: "{installed_path}/template.md" # optional, can be omitted
instructions: "{installed_path}/instructions.md" # optional, can be omitted
validation: "{installed_path}/checklist.md" # optional, can be omitted

# Output configuration
default_output_file: "{output_folder}/{file.md}" # optional, can be omitted
validation_output_file: "{output_folder}/{file-validation-report.md}" # optional, can be omitted

# Tool Requirements (MCP Required Tools or other tools needed to run this workflow)
required_tools: #optional, can be omitted
  - "Tool Name": #example, can be omitted if none
      description: "Description of why this tool is needed"
      link: "https://link-to-tool.com"

# Web Bundle Configuration (optional - for web-deployable workflows)
# IMPORTANT: Web bundles are self-contained and cannot use config_source variables
# All referenced files must be listed in web_bundle_files
web_bundle: #optional, can be omitted
  name: "{WORKFLOW_CODE}"
  description: "{WORKFLOW_DESCRIPTION}"
  author: "BMad"

  # Core workflow files (paths relative to bmad/ root)
  instructions: "bmad/{module-code}/workflows/{workflow-code}/instructions.md"
  validation: "bmad/{module-code}/workflows/{workflow-code}/checklist.md"
  template: "bmad/{module-code}/workflows/{workflow-code}/template.md" # if document workflow

  # Reference any data files or additional workflows (no config_source allowed)
  # brain_techniques: "bmad/{module-code}/workflows/{workflow-code}/data-file.csv"
  # sub_workflow: "bmad/{module-code}/workflows/other-workflow/workflow.yaml"

  # CRITICAL: List ALL files used by this workflow
  # This includes instructions, validation, templates, data files,
  # and any files referenced within those files
  web_bundle_files:
    - "bmad/{module-code}/workflows/{workflow-code}/instructions.md"
    - "bmad/{module-code}/workflows/{workflow-code}/checklist.md"
    - "bmad/{module-code}/workflows/{workflow-code}/template.md"
    # Add ALL referenced files here - examine instructions.md and template.md
    # for any file paths and include them all
    # - "bmad/{module-code}/workflows/{workflow-code}/data/example.csv"
    # - "bmad/{module-code}/templates/shared-template.md"
