# Workflow Status - Master Router and Status Tracker
name: workflow-status
description: 'Lightweight status checker - answers "what should I do now?" for any agent. Reads simple key-value status file for instant parsing. Use workflow-init for new projects.'
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/workflow-status"
instructions: "{installed_path}/instructions.md"

# Template for status file creation (used by workflow-init)
template: "{installed_path}/workflow-status-template.md"

# Path definitions for project types
path_files: "{installed_path}/paths/"

# Output configuration - reads existing status
default_output_file: "{output_folder}/bmm-workflow-status.md"

standalone: true

web_bundle: false
