# Storytelling Workflow Configuration
name: "storytelling"
description: "Craft compelling narratives using proven story frameworks and techniques. This workflow guides users through structured narrative development, applying appropriate story frameworks to create emotionally resonant and engaging stories for any purpose."
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/bmad/cis/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Optional inputs for context
recommended_inputs:
  - story_context: "Context document passed via data attribute"
  - previous_stories: "{output_folder}/story-*.md"

# Context can be provided via data attribute when invoking
# Example: data="{path}/brand-info.md" provides brand context

# Module path and component files
installed_path: "{project-root}/bmad/cis/workflows/storytelling"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"

# Required Data Files
story_frameworks: "{installed_path}/story-types.csv"

# Output configuration
default_output_file: "{output_folder}/story-{{date}}.md"

standalone: true

web_bundle:
  name: "storytelling"
  description: "Craft compelling narratives using proven story frameworks and techniques. This workflow guides users through structured narrative development, applying appropriate story frameworks to create emotionally resonant and engaging stories for any purpose."
  author: "BMad"
  instructions: "bmad/cis/workflows/storytelling/instructions.md"
  template: "bmad/cis/workflows/storytelling/template.md"
  web_bundle_files:
    - "bmad/cis/workflows/storytelling/instructions.md"
    - "bmad/cis/workflows/storytelling/template.md"
    - "bmad/cis/workflows/storytelling/story-types.csv"
